db-config:
  dbname: castdb
  dbpass: *********************
  dbhost: localhost
  dbport: 5432
  dbuser: *********************
component-root: cast.components
email-config:
  credentials-path: /home/jacrod2901/geese/cowin/secrets/credentials.json
  token-path: /home/jacrod2901/geese/cowin/secrets/token.json
  email-from: dev@orcasol.net
  email-subject: no-reply Vax Alert!! 
  email-content: THIS IS A NOTIFICATION ALERT FOR VACCINE AVAILABILITY
json-config:
  json-file-path: /home/jacrod2901/geese/cowin/resources/document.json
